config/routes.rb
Rails.application.routes.draw do
  root 'garments#index'

  get 'garments/' => 'garments#index'
  post 'garments/' => 'garments#create'
  get 'garments/new' => 'garments#new', as: :new_garment
  get 'garments/:id' => 'garments#show', as: :garment
  get 'garments/:id/edit' => 'garments#edit', as: :edit_garment
  put 'garments/:id' => 'garments#update'
  patch 'garments/:id' => 'garments#update'
  delete 'garments/:id' => 'garments#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garment.rb
class Garment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/garments_controller.rb
class GarmentsController < ApplicationController
  before_action :set_garment, only: [:show, :edit, :update, :destroy]

  def index
    @garments = Garment.all
  end

  def show
  end

  def new
    @garment = Garment.new
  end

  def create
    @garment = Garment.new(garment_params)

    if @garment.save
      redirect_to @garment
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @garment.update_attributes(garment_params)
      redirect_to @garment
    else
      render :edit
    end
  end

  def destroy
    @garment.destroy
    redirect_to garments_path
  end

private
  def garment_params
    params.require(:garment).permit(:name, :color, :material, :price, :cool)
  end

  def set_garment
    @garment = Garment.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/garments_helper.rb
module GarmentsHelper
end

app/views/garments/_form.html.erb
<%= form_for @garment do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>
  <div>
    <%= f.label :material %>
    <%= f.text_field :material %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.number_field :price, :step => 0.25 %>
  </div>
  <div>
    <%= f.label :cool %>
    <%= f.check_box :cool %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/garments/edit.html.erb
<h1>Edit this Garment</h1>

<%= render 'form' %>

app/views/garments/index.html.erb
<h1>KaKeStyle Garments</h1>

<ul>
  <% @garments.each do |garment| %>
    <li>
      <%= link_to garment.name.capitalize, garment_path(garment) %>
      <%= link_to 'Edit', edit_garment_path(garment) %>
      <%= link_to 'Delete', garment, method: :delete, data: {confirm: 'Are you sure?'} %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add a new garment', new_garment_path %>

app/views/garments/new.html.erb
<h1>New Garment</h1>

<%= render 'form' %>

app/views/garments/show.html.erb
<h1><%= @garment.name.capitalize %></h1>

<table>
  <thead>
    <td>
      Color
    </td>
    <td>
      Material
    </td>
    <td>
      Price
    </td>
    <td>
      Cool?
    </td>
  </thead>
  <tbody>
    <td>
      <%= @garment.color %>
    </td>
    <td>
      <%= @garment.material %>
    </td>
    <td>
      $<%= @garment.price %>0
    </td>
    <td>
      <% if @garment.cool %>
        Totally!
      <% else %>
        Nah, bruh.
      <% end %>
    </td>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kakestyle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>